(in-package #:elisp)

(define-condition elisp-load-error (error)
  ((path :initarg :path :reader elisp-load-error-path)
   (form-index :initarg :form-index :reader elisp-load-error-form-index)
   (form :initarg :form :reader elisp-load-error-form)
   (cause :initarg :cause :reader elisp-load-error-cause)
   (inventory-entry :initarg :inventory-entry :reader elisp-load-error-inventory-entry))
  (:report (lambda (c s)
             (format s "ELisp load error in ~A (form ~D):~%  ~S~%~A~@[~%Inventory: ~A~]"
                     (elisp-load-error-path c)
                     (elisp-load-error-form-index c)
                     (elisp-load-error-form c)
                     (elisp-load-error-cause c)
                     (elisp-load-error-inventory-entry c)))))

(cl:defun load-bootstrap-set (&key (project-root (uiop:getcwd))
                                   (manifest #p"clemacs/contract/bootstrap.files")
                                   (limit nil))
  (let* ((project-root (uiop:ensure-directory-pathname project-root))
         (manifest (merge-pathnames manifest project-root))
         (loaded 0))
    (with-open-file (in manifest :external-format :utf-8)
      (loop for line = (read-line in nil nil)
            while line do
              (let ((line (string-trim '(#\Space #\Tab #\Return #\Newline) line)))
                (when (and (> (length line) 0)
                           (not (char= (char line 0) #\#)))
                  (when (and limit (>= loaded limit))
                    (return))
                  (load-elisp-file (merge-pathnames line project-root))
                  (incf loaded)))))
    0))
