(in-package #:clemacs.test)

(fiveam:def-suite clemacs-smoke)
(fiveam:in-suite clemacs-smoke)
(fiveam:def-suite clemacs-micro)

(defun %project-root ()
  (uiop:ensure-directory-pathname
   (or (uiop:getenv "MISE_PROJECT_ROOT")
       (uiop:pathname-parent-directory-pathname
        (asdf:system-source-directory :clemacs)))))

(defun %reference-emacs ()
  (or (uiop:getenv "CLEMACS_REFERENCE_EMACS")
      (and (probe-file #p"/opt/homebrew/bin/emacs") "/opt/homebrew/bin/emacs")
      (and (probe-file #p"/usr/local/bin/emacs") "/usr/local/bin/emacs")
      "emacs"))

(defun %maybe-emacs-prin1 (expr)
  (when (uiop:getenv "CLEMACS_SKIP_REFERENCE_EMACS")
    (return-from %maybe-emacs-prin1 :disabled))
  (multiple-value-bind (out err code)
      (handler-case
          (uiop:run-program
           (list (%reference-emacs) "-Q" "--batch" "--eval"
                 (format nil "(let ((print-escape-newlines t) (print-escape-control-characters t)) (prin1 ~A) (terpri))"
                         expr))
           :output :string
           :error-output :string
           :ignore-error-status t)
        (error ()
          (return-from %maybe-emacs-prin1 nil)))
    (when (not (eql code 0))
      (error "reference Emacs failed (~S): ~A (expr: ~A)" code err expr))
    (string-trim '(#\Space #\Tab #\Newline #\Return) out)))

(defun %maybe-emacs-prin1/batch (name+exprs &key (label "batch"))
  (when (uiop:getenv "CLEMACS_SKIP_REFERENCE_EMACS")
    (return-from %maybe-emacs-prin1/batch :disabled))
  (let ((batch-mode (uiop:getenv "CLEMACS_REFERENCE_EMACS_BATCH")))
    (when (and batch-mode (member batch-mode '("0" "false" "FALSE" "no" "NO") :test #'string=))
      (let ((table (make-hash-table :test #'equal)))
        (dolist (pair name+exprs)
          (let ((out (%maybe-emacs-prin1 (cdr pair))))
            (cond
             ((eq out :disabled) (return-from %maybe-emacs-prin1/batch :disabled))
             ((null out) (return-from %maybe-emacs-prin1/batch nil))
             (t (setf (gethash (car pair) table) out)))))
        (return-from %maybe-emacs-prin1/batch table))))
  (handler-case
      (uiop:with-temporary-file (:stream script
                                 :pathname script-path
                                 :prefix "clemacs-ref-emacs."
                                 :suffix ".el"
                                 :direction :output
                                 :external-format :utf-8)
        (format script ";; Auto-generated by clemacs microtests (~A).~%" label)
        (format script "(setq clemacs--microtest-exprs '(")
        (dolist (pair name+exprs)
          (destructuring-bind (name . expr) pair
            (format script "(~S . ~S)~%" name expr)))
        (format script "))~%")
        (write-string
         "(let ((print-escape-newlines t)
      (print-escape-control-characters t)
      (out nil))
  (dolist (item clemacs--microtest-exprs)
    (let ((name (car item)) (expr (cdr item)))
      (condition-case err
          (let* ((form (car (read-from-string expr)))
                 (val (eval form))
                 (printed (prin1-to-string val)))
            (push (cons name printed) out))
        (error (push (list name :error (prin1-to-string err)) out)))))
  (prin1 (nreverse out))
  (terpri))
"
         script)
        (finish-output script)
        (multiple-value-bind (out err code)
            (uiop:run-program
             (list (%reference-emacs) "-Q" "--batch" "-l" (namestring script-path))
             :output :string
             :error-output :string
             :ignore-error-status t)
          (when (not (eql code 0))
            (error "reference Emacs failed (~S): ~A (label: ~A)" code err label))
          (let* ((trimmed (string-trim '(#\Space #\Tab #\Newline #\Return) out))
                 (results (read-from-string trimmed))
                 (table (make-hash-table :test #'equal)))
            (dolist (item results)
              (cond
               ((and (consp item) (stringp (car item)) (stringp (cdr item)))
                (setf (gethash (car item) table) (cdr item)))
               ((and (consp item)
                     (stringp (first item))
                     (eq (second item) :error)
                     (stringp (third item)))
                (let* ((name (first item))
                       (expr (cdr (assoc name name+exprs :test #'string=)))
                       (msg (third item)))
                  (error "reference Emacs failed: ~A (expr: ~A; err: ~A)" name expr msg)))
               (t
                (error "Bad reference Emacs batch result entry: ~S" item))))
            table)))
    (error ()
      nil)))

(defun %clemacs-prin1 (value)
  (labels ((p1 (v)
             (cond
              ((and (vectorp v) (not (elisp::stringp v)))
               (with-output-to-string (s)
                 (write-char #\[ s)
                 (dotimes (i (length v))
                   (when (> i 0) (write-char #\Space s))
                   (write-string (p1 (aref v i)) s))
               (write-char #\] s)))
              (t
               (let ((elisp::print-escape-newlines t)
                     (elisp::print-escape-control-characters t))
                 (elisp::%elisp-string->cl-string
                  (elisp:prin1-to-string v)))))))
    (p1 value)))

(defun %elisp-eval-1 (string)
  (let ((*package* (find-package "ELISP"))
        (*readtable* (elisp::%ensure-elisp-readtable)))
    (multiple-value-bind (sanitized _insertions)
        (elisp::%sanitize-elisp-source/colon-tokens string)
      (declare (ignore _insertions))
      (elisp:eval (read-from-string sanitized)))))

(defun %elisp-read-1 (string)
  (let ((*package* (find-package "ELISP"))
        (*readtable* (elisp::%ensure-elisp-readtable)))
    (multiple-value-bind (sanitized _insertions)
        (elisp::%sanitize-elisp-source/colon-tokens string)
      (declare (ignore _insertions))
      (read-from-string sanitized))))

(fiveam:test substrate-basics
  (let ((version (clemacs:substrate-version))
        (platform (clemacs:substrate-platform)))
    (fiveam:is (and (stringp version) (> (length version) 0)))
    (fiveam:is (and (stringp platform) (> (length platform) 0))))

  (fiveam:is (= (clemacs:substrate-parse-int "42") 42))
  (fiveam:signals clemacs:clemacs-substrate-error
    (clemacs:substrate-parse-int "nope")))

(fiveam:test handle-table
  (let* ((table (clemacs:make-handle-table))
         (h1 (clemacs:handle-alloc table 'a))
         (h2 (clemacs:handle-alloc table 'b)))
    (fiveam:is (eql (clemacs:handle-get table h1) 'a))
    (fiveam:is (eql (clemacs:handle-get table h2) 'b))
    (fiveam:is (clemacs:handle-free table h1))
    (fiveam:signals error
      (clemacs:handle-get table h1))
    (let ((h3 (clemacs:handle-alloc table 'c)))
      (fiveam:is (eql h3 h1))
      (fiveam:is (eql (clemacs:handle-get table h3) 'c)))))

(fiveam:test buffer-edit-basics
  (let ((b (clemacs:make-buffer :content "")))
    (fiveam:is (= (clemacs:buffer-length b) 0))
    (clemacs:buffer-insert-string b "abc")
    (fiveam:is (string= (clemacs:buffer-text b) "abc"))
    (fiveam:is (= (clemacs:buffer-point b) 3))
    (clemacs:buffer-backward-char b)
    (clemacs:buffer-insert-char b #\X)
    (fiveam:is (string= (clemacs:buffer-text b) "abXc"))
    (fiveam:is (= (clemacs:buffer-point b) 3))
    (clemacs:buffer-delete-backward b)
    (fiveam:is (string= (clemacs:buffer-text b) "abc"))
    (fiveam:is (= (clemacs:buffer-point b) 2))
    (values)))

(fiveam:test buffer-vertical-motion
  (let* ((b (clemacs:make-buffer :content (format nil "abc~%line2")))
         (initial-point (clemacs:buffer-point b)))
    (fiveam:is (= initial-point 9))
    (multiple-value-bind (b2 goal)
        (clemacs:buffer-move-vertical b -1 :goal-column nil)
      (declare (ignore b2))
      (fiveam:is (= goal 5)))
    (multiple-value-bind (line col) (clemacs::buffer-line-column b)
      (fiveam:is (= line 0))
      (fiveam:is (= col 3)))))

(fiveam:test elisp-compat
  (let ((exprs '(("(progn (setq x 1) x)" . "1")
                 ("(let ((p nil)) (setq p (plist-put p 'a 1)) (plist-get p 'a))" . "1")
                 ("[1 2 3]" . "[1 2 3]")
                 ("?a" . "97"))))
    (dolist (item exprs)
      (destructuring-bind (expr . expected) item
        (let ((value (%elisp-eval-1 expr)))
          (fiveam:is (string= (%clemacs-prin1 value) expected))
          (let ((emacs-out (%maybe-emacs-prin1 expr)))
            (cond
             ((eq emacs-out :disabled) nil)
             (emacs-out (fiveam:is (string= emacs-out expected)))
             (t (fiveam:skip "emacs not on PATH")))))))))

(fiveam:test elisp-reader-backquote
  (let* ((form (%elisp-read-1 "`(a ,b ,@c)")))
    (fiveam:is (and (consp form) (string= (cl:symbol-name (car form)) "`")))
    (let* ((elisp (find-package "ELISP"))
           (comma (cl:intern "," elisp))
           (comma-at (cl:intern ",@" elisp)))
      (fiveam:is
       (equal
        (second form)
        (list (cl:intern "A" elisp)
              (list comma (cl:intern "B" elisp))
              (list comma-at (cl:intern "C" elisp))))))))

(fiveam:test elisp-backquote-vectors
  (let* ((project-root
           (%project-root))
         (backquote-el (merge-pathnames #p"lisp/emacs-lisp/backquote.el" project-root)))
    (unless (fboundp 'elisp::backquote)
      (elisp::load-elisp-file backquote-el))
    (let ((value (%elisp-eval-1 "`(x [0 255])")))
    (fiveam:is (and (consp value) (eql (car value) 'elisp::x)))
    (fiveam:is (vectorp (cadr value)))
    (fiveam:is (= (length (cadr value)) 2))
    (fiveam:is (= (aref (cadr value) 0) 0))
    (fiveam:is (= (aref (cadr value) 1) 255)))))

(fiveam:test elisp-pcase-dolist-simple
  (let ((value
          (%elisp-eval-1
           "(let ((states '((a t 1) (b nil 2))) (out nil)) (pcase-dolist (`(,v ,l ,val) states) (setq out (cons v out))) out)")))
    (fiveam:is (string= (%clemacs-prin1 value) "(b a)"))))

(defun %read-semantics-microtests (&key (project-root (%project-root)))
  (let ((path (merge-pathnames #p"clemacs/contract/semantics.microtests.sexp"
                               project-root)))
    (with-open-file (in path :direction :input :external-format :utf-8)
      (read in))))

(defun %microtest-name-filter ()
  (let ((raw (uiop:getenv "CLEMACS_MICROTEST_NAME")))
    (when (and raw (> (length raw) 0))
      (let ((needles
              (remove-if
               #'null
               (mapcar
                (lambda (s)
                  (let ((s (string-trim '(#\Space #\Tab #\Newline #\Return) s)))
                    (and (> (length s) 0) s)))
                (uiop:split-string raw :separator ",")))))
        (lambda (name)
          (and (stringp name)
               (some (lambda (needle) (search needle name)) needles)))))))

(fiveam:in-suite clemacs-micro)
(fiveam:test elisp-semantics-microtests
  ;; Keep microtests load-order independent: some entries exercise the shipped
  ;; backquote DSL (symbols like `|`| and `|,|`) which needs `backquote.el`
  ;; loaded to define the expander.
  (let* ((project-root (%project-root))
         (backquote-el (merge-pathnames #p"lisp/emacs-lisp/backquote.el" project-root)))
    (unless (fboundp 'elisp::backquote)
      (elisp::load-elisp-file backquote-el)))
  ;; `elisp:eval` uses CL:EVAL, so macros must be present at compile time.
  ;; Preload the ported `cl-macs` subset so microtests can use `cl-flet*`
  ;; without relying on (require ...) inside the evaluated expression.
  (let* ((project-root (%project-root))
         (cl-macs-el
           (merge-pathnames #p"clemacs/ported/lisp/emacs-lisp/cl-macs.el"
                            project-root)))
    (unless (fboundp 'elisp::cl-flet*)
      (elisp::load-elisp-file cl-macs-el)))
  (let* ((tests (%read-semantics-microtests))
         (name-filter (%microtest-name-filter)))
    (when name-filter
      (setf tests
            (remove-if-not (lambda (entry) (funcall name-filter (getf entry :name))) tests))
      (when (null tests)
        (error "No semantics microtests match CLEMACS_MICROTEST_NAME=~S"
               (uiop:getenv "CLEMACS_MICROTEST_NAME"))))
    (let ((limit-raw (uiop:getenv "CLEMACS_MICROTEST_LIMIT")))
      (when (and limit-raw (> (length limit-raw) 0))
        (let ((n (ignore-errors (parse-integer limit-raw :junk-allowed t))))
          (when (and (integerp n) (> n 0))
            (setf tests (subseq tests 0 (min n (length tests))))))))
    (let* ((match-items
             (mapcar (lambda (entry) (cons (getf entry :name) (getf entry :expr)))
                     (remove-if-not (lambda (entry) (eql (getf entry :emacs) :match)) tests)))
           (emacs-outs
             (and match-items
                  (%maybe-emacs-prin1/batch match-items :label "semantics microtests"))))
      (dolist (test tests)
        (let* ((name (getf test :name))
               (expr (getf test :expr))
               (expected (getf test :expected))
               (emacs (getf test :emacs)))
          (unless (and (stringp name) (stringp expr) (stringp expected))
            (error "Bad semantics microtest entry: ~S" test))
          (let* ((value
                   (handler-case
                       (%elisp-eval-1 expr)
                     (error (e)
                       (error "~A: unexpected error ~A for expr: ~A" name e expr))))
                 (clemacs-out (%clemacs-prin1 value)))
            (fiveam:is (string= clemacs-out expected)
                       "~A: expected ~S, got ~S for expr: ~A"
                       name expected clemacs-out expr)
            (when (eql emacs :match)
              (cond
               ((eq emacs-outs :disabled) nil)
               ((hash-table-p emacs-outs)
                (multiple-value-bind (emacs-out presentp)
                    (gethash name emacs-outs)
                  (unless presentp
                    (error "Missing reference Emacs batch result for: ~A" name))
                  (fiveam:is (string= emacs-out clemacs-out)
                             "~A: clemacs != emacs: ~S vs ~S for expr: ~A"
                             name clemacs-out emacs-out expr)))
               (t
                (fiveam:skip "reference Emacs not available (set CLEMACS_REFERENCE_EMACS)"))))))))))


(defun run-micro (&key (stream *standard-output*))
  (let ((fiveam:*test-dribble* stream))
    (multiple-value-bind (ok failed skipped)
        (fiveam:run! 'clemacs-micro)
      (declare (ignore failed skipped))
      (format stream "clemacs micro: ~:[FAIL~;ok~]~%" ok)
      (finish-output stream)
      (if ok 0 1))))

(defun run-smoke (&key (stream *standard-output*))
  (let ((fiveam:*test-dribble* stream))
    (multiple-value-bind (ok failed skipped)
        (fiveam:run! 'clemacs-smoke)
      (declare (ignore failed skipped))
      (format stream "clemacs smoke: ~:[FAIL~;ok~]~%" ok)
      (finish-output stream)
      (if ok 0 1))))
